name: Python package test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Install package
        run: pip install .

      - name: Test treefeeder command
        run: |
          treefeeder . --all
          treefeeder . -P "*.py"
          treefeeder . --pattern "*.md"
          treefeeder . -I "*.py"
          treefeeder . --ignore "*.md"
          treefeeder . -S ", "
